name = "tts-translate"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[env.production]
# Environment variables are set in Cloudflare Dashboard
# Go to Pages > Settings > Environment variables
# Add: OPENAI_API_KEY = your-api-key
